name: e-commerce-scraping
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.10.0
  - google_api_python_client==2.34.0
  - google_auth_oauthlib==0.4.6
  - lxml=4.7.1
  - numpy=1.21.5
  - openpyxl=3.0.9
  - pandas=1.3.5
  - protobuf==3.19.1
  - python=3.8.12
  - requests=2.26.0
  - rich==10.16.2
  - scraping==0.0.3
  - pip:
    - selenium==3.141.0
    - selenium-requests==1.3.3
