name: e-commerce-scraping
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - lxml
  - numpy
  - openpyxl
  - pandas
  - protobuf
  - python
  - requests
  - pip:
    - google_api_python_client
    - google_auth_oauthlib
    - selenium
    - selenium-requests
    - scraping
    - webdriver-manager
